"use client";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown, Sparkles } from "lucide-react";
import { Elephant, Lotus } from "@/components/HeritageMotifs";
import { InvitationCard } from "@/components/InvitationCard";
import { Itinerary } from "@/components/Itinerary";
import { RSVPForm } from "@/components/RSVPForm";
import { wedding } from "@/lib/wedding-data";
export default function Home() { const [opened, setOpened] = useState(false); const rsvpEnabled = wedding.features.rsvpEnabled; return <main><AnimatePresence>{!opened && <motion.section key="cover" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0, scale: 1.03 }} transition={{ duration: .65 }} className="relative flex min-h-svh overflow-hidden bg-royal-radial px-5 py-10 text-center text-ivory"><motion.div initial={{ opacity: 0, y: 25 }} animate={{ opacity: .2, y: 0 }} transition={{ delay: .25, duration: 1.2 }} className="absolute left-1/2 top-8 w-[34rem] max-w-[120%] -translate-x-1/2 text-gold-300"><Elephant className="mx-auto h-auto w-full"/></motion.div><div className="relative z-10 m-auto max-w-xl"><Lotus className="mx-auto h-16 w-28 text-gold-300"/><p className="mt-7 text-sm tracking-[.25em] text-gold-300">{wedding.invocation}</p><p className="mt-12 text-xs font-semibold uppercase tracking-[.32em] text-gold-300">A celebration of love</p><h1 className="mt-4 font-display text-6xl leading-none sm:text-8xl">{wedding.couple}</h1><p className="mt-6 text-lg italic text-gold-300">19 &amp; 20 September 2026</p><button onClick={() => setOpened(true)} className="focus-ring mt-12 inline-flex items-center gap-2 rounded-sm border border-gold-300 bg-gold-400 px-6 py-3 font-semibold text-crimson-900 shadow-lg transition hover:bg-gold-300"><Sparkles size={18}/>Open invitation</button></div><ChevronDown className="absolute bottom-6 left-1/2 -translate-x-1/2 animate-bounce text-gold-300"/></motion.section>}</AnimatePresence>{opened && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}><header className="sticky top-0 z-20 border-b border-gold-400/30 bg-crimson-900/95 px-4 py-3 text-ivory backdrop-blur"><nav className="mx-auto flex max-w-5xl items-center justify-between gap-4"><a href="#top" className="font-display text-xl">M <span className="text-gold-300">&amp;</span> S</a><div className="flex gap-4 text-xs font-semibold uppercase tracking-wider sm:text-sm"><a className="hover:text-gold-300" href="#invitation">Invitation</a><a className="hover:text-gold-300" href="#itinerary">Events</a>{rsvpEnabled && <a className="hover:text-gold-300" href="#rsvp">RSVP</a>}</div></nav></header><div id="top"><InvitationCard/><Itinerary/>{rsvpEnabled && <RSVPForm/>}</div><footer className="bg-crimson-900 px-4 py-10 text-center text-ivory"><Lotus className="mx-auto h-10 w-16 text-gold-300"/><p className="mt-4 font-display text-2xl">{wedding.couple}</p><p className="mt-2 text-sm text-gold-300">With love, we await your presence.</p></footer></motion.div>}</main>; }
